export { Skeleton } from "@/components/ui/Skeleton";
export {
  AdminDashboardSkeleton,
  AdminDetailPanelSkeleton,
  AnnouncementsPageSkeleton,
  AssignmentsListSkeleton,
  AuditLogsPageSkeleton,
  CardGridSkeleton,
  DetailPageSkeleton,
  DiscussionListSkeleton,
  FiltersBarSkeleton,
  ListItemsSkeleton,
  LmsDashboardSkeleton,
  PortalLayoutSkeleton,
  PortalPageHeaderSkeleton,
  PortalTitleSkeleton,
  ProfilePageSkeleton,
  QuickLinksSkeleton,
  SettingsPageSkeleton,
  SecurityPageSkeleton,
  StatCardsSkeleton,
  TablePageSkeleton,
  TableRowsSkeleton,
} from "@/components/skeletons/PortalSkeletons";
