import prisma from "../config/database.js";
import { generateCertificateId } from "../utils/certificateGenerator.js";
import { hasStaffAccess } from "../middleware/auth.js";

/**
 * Get user's certificates
 */
export const getUserCertificates = async (req, res) => {
  try {
    const userId = req.user.uid;

    if (!userId) {
      return res.status(400).json({
        success: false,
        message: "User ID not found",
      });
    }

    const certificates = await prisma.certificate.findMany({
      where: { userId },
      include: {
        course: {
          select: {
            id: true,
            title: true,
            slug: true,
          },
        },
        user: {
          select: {
            name: true,
            email: true,
          },
        },
      },
      orderBy: { issuedAt: "desc" },
    });

    res.json({
      success: true,
      data: certificates.map((cert) => ({
        id: cert.id,
        certificateId: cert.certificateId,
        courseTitle: cert.course.title,
        courseId: cert.course.id,
        userName: cert.user.name,
        issuedAt: cert.issuedAt,
        pdfUrl: cert.pdfUrl,
        qrCodeUrl: cert.qrCodeUrl,
      })),
    });
  } catch (error) {
    console.error("Get certificates error:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch certificates",
      error: error.message,
    });
  }
};

/**
 * Generate certificate when course is completed
 */
export const generateCertificate = async (req, res) => {
  try {
    const userId = req.user.uid;
    const { courseId } = req.body;

    if (!courseId) {
      return res.status(400).json({
        success: false,
        message: "courseId is required",
      });
    }

    // Check if course exists
    const course = await prisma.course.findUnique({
      where: { id: courseId },
    });

    if (!course) {
      return res.status(404).json({
        success: false,
        message: "Course not found",
      });
    }

    // Check if certificate already exists
    const existingCert = await prisma.certificate.findUnique({
      where: {
        userId_courseId: {
          userId,
          courseId,
        },
      },
    });

    if (existingCert) {
      return res.status(400).json({
        success: false,
        message: "Certificate already issued for this course",
      });
    }

    // Get user details
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { name: true, email: true },
    });

    // Generate certificate
    const certificateId = generateCertificateId();
    
    const certificate = await prisma.certificate.create({
      data: {
        certificateId,
        userId,
        courseId,
        issuedAt: new Date(),
        // URLs would be generated by a certificate service
        // For now, we'll leave them null
        pdfUrl: null,
        qrCodeUrl: null,
      },
      include: {
        course: {
          select: {
            title: true,
          },
        },
        user: {
          select: {
            name: true,
          },
        },
      },
    });

    res.status(201).json({
      success: true,
      message: "Certificate generated successfully",
      data: {
        id: certificate.id,
        certificateId: certificate.certificateId,
        courseTitle: certificate.course.title,
        userName: certificate.user.name,
        issuedAt: certificate.issuedAt,
        pdfUrl: certificate.pdfUrl,
        qrCodeUrl: certificate.qrCodeUrl,
      },
    });
  } catch (error) {
    console.error("Generate certificate error:", error);
    res.status(500).json({
      success: false,
      message: "Failed to generate certificate",
      error: error.message,
    });
  }
};

/**
 * Get certificate by ID (for verification)
 */
export const getCertificateById = async (req, res) => {
  try {
    const { certificateId } = req.params;

    const certificate = await prisma.certificate.findUnique({
      where: { certificateId },
      include: {
        course: {
          select: {
            title: true,
            slug: true,
          },
        },
        user: {
          select: {
            name: true,
            email: true,
          },
        },
      },
    });

    if (!certificate) {
      return res.status(404).json({
        success: false,
        message: "Certificate not found",
      });
    }

    res.json({
      success: true,
      data: {
        id: certificate.id,
        certificateId: certificate.certificateId,
        courseTitle: certificate.course.title,
        courseSig: certificate.course.slug,
        studentName: certificate.user.name,
        studentEmail: certificate.user.email,
        issuedAt: certificate.issuedAt,
        pdfUrl: certificate.pdfUrl,
        qrCodeUrl: certificate.qrCodeUrl,
      },
    });
  } catch (error) {
    console.error("Get certificate error:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch certificate",
      error: error.message,
    });
  }
};

/**
 * List all certificates (admin)
 */
export const getAllCertificates = async (req, res) => {
  try {
    // Check if user is admin
    if (!hasStaffAccess(req.user)) {
      return res.status(403).json({
        success: false,
        message: "Forbidden: Only admins can view all certificates",
      });
    }

    const certificates = await prisma.certificate.findMany({
      include: {
        course: {
          select: {
            title: true,
          },
        },
        user: {
          select: {
            name: true,
            email: true,
          },
        },
      },
      orderBy: { issuedAt: "desc" },
    });

    res.json({
      success: true,
      data: certificates,
    });
  } catch (error) {
    console.error("Get all certificates error:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch certificates",
      error: error.message,
    });
  }
};
